export const areasInChennai = [
    { value: 'Adambakkam', label: 'Adambakkam' },
    { value: 'Adyar', label: 'Adyar' },
    { value: 'Alandur', label: 'Alandur' },
    { value: 'Alwarpet', label: 'Alwarpet' },
    { value: 'Alwarthirunagar', label: 'Alwarthirunagar' },
    { value: 'Ambattur', label: 'Ambattur' },
    { value: 'Aminjikarai', label: 'Aminjikarai' },
    { value: 'Anna Nagar', label: 'Anna Nagar' },
    { value: 'Arumbakkam', label: 'Arumbakkam' },
    { value: 'Ashok Nagar', label: 'Ashok Nagar' },
    { value: 'Avadi', label: 'Avadi' },
    { value: 'Ayanavaram', label: 'Ayanavaram' },
    { value: 'Besant Nagar', label: 'Besant Nagar' },
    { value: 'Chengalpattu', label: 'Chengalpattu' },
    { value: 'Chitlapakkam', label: 'Chitlapakkam' },
    { value: 'Choolaimedu', label: 'Choolaimedu' },
    { value: 'Chromepet', label: 'Chromepet' },
    { value: 'Egmore', label: 'Egmore' },
    { value: 'Ekkaduthangal', label: 'Ekkaduthangal' },
    { value: 'Ennore', label: 'Ennore' },
    { value: 'Foreshore Estate', label: 'Foreshore Estate' },
    { value: 'George Town', label: 'George Town' },
    { value: 'Gopalapuram', label: 'Gopalapuram' },
    { value: 'Guindy', label: 'Guindy' },
    { value: 'IIT Madras', label: 'IIT Madras' },
    { value: 'Injambakkam', label: 'Injambakkam' },
    { value: 'Iyyappanthangal', label: 'Iyyappanthangal' },
    { value: 'K.K. Nagar', label: 'K.K. Nagar' },
    { value: 'K.K. Nagar West', label: 'K.K. Nagar West' },
    { value: 'Kodambakkam', label: 'Kodambakkam' },
    { value: 'Kolathur', label: 'Kolathur' },
    { value: 'Korattur', label: 'Korattur' },
    { value: 'Kottivakkam', label: 'Kottivakkam' },
    { value: 'Kotturpuram', label: 'Kotturpuram' },
    { value: 'Koyambedu', label: 'Koyambedu' },
    { value: 'Kundrathur', label: 'Kundrathur' },
    { value: 'Madhavaram', label: 'Madhavaram' },
    { value: 'Madipakkam', label: 'Madipakkam' },
    { value: 'Maduravoyal', label: 'Maduravoyal' },
    { value: 'Manali', label: 'Manali' },
    { value: 'Manapakkam', label: 'Manapakkam' },
    { value: 'Medavakkam', label: 'Medavakkam' },
    { value: 'Meenambakkam', label: 'Meenambakkam' },
    { value: 'Mogappair', label: 'Mogappair' },
    { value: 'Mogappair East', label: 'Mogappair East' },
    { value: 'Mogappair West', label: 'Mogappair West' },
    { value: 'Mudichur', label: 'Mudichur' },
    { value: 'Mylapore', label: 'Mylapore' },
    { value: 'Nandanam', label: 'Nandanam' },
    { value: 'Nanganallur', label: 'Nanganallur' },
    { value: 'Nungambakkam', label: 'Nungambakkam' },
    { value: 'Otteri', label: 'Otteri' },
    { value: 'Padi', label: 'Padi' },
    { value: 'Palavakkam', label: 'Palavakkam' },
    { value: 'Pallavaram', label: 'Pallavaram' },
    { value: 'Pallikaranai', label: 'Pallikaranai' },
    { value: 'Pammal', label: 'Pammal' },
    { value: 'Park Town', label: 'Park Town' },
    { value: 'Parrys', label: 'Parrys' },
    { value: 'Perambur', label: 'Perambur' },
    { value: 'Perungudi', label: 'Perungudi' },
    { value: 'Poonamallee', label: 'Poonamallee' },
    { value: 'Porur', label: 'Porur' },
    { value: 'Pudupet', label: 'Pudupet' },
    { value: 'Purasaiwalkam', label: 'Purasaiwalkam' },
    { value: 'Raj Bhavan', label: 'Raj Bhavan' },
    { value: 'Ramapuram', label: 'Ramapuram' },
    { value: 'Royapettah', label: 'Royapettah' },
    { value: 'Saidapet', label: 'Saidapet' },
    { value: 'Saligramam', label: 'Saligramam' },
    { value: 'Santhome', label: 'Santhome' },
    { value: 'Selaiyur', label: 'Selaiyur' },
    { value: 'Shenoy Nagar', label: 'Shenoy Nagar' },
    { value: 'Sholinganallur', label: 'Sholinganallur' },
    { value: 'Sithalapakkam', label: 'Sithalapakkam' },
    { value: 'Sowcarpet', label: 'Sowcarpet' },
    { value: 'St. Thomas Mount', label: 'St. Thomas Mount' },
    { value: 'Teynampet', label: 'Teynampet' },
    { value: 'Tharamani', label: 'Tharamani' },
    { value: 'T. Nagar', label: 'T. Nagar' },
    { value: 'Thirumangalam', label: 'Thirumangalam' },
    { value: 'Thirumazhisai', label: 'Thirumazhisai' },
    { value: 'Thiruninravur', label: 'Thiruninravur' },
    { value: 'Thiruvanmiyur', label: 'Thiruvanmiyur' },
    { value: 'Tiruverkadu', label: 'Tiruverkadu' },
    { value: 'Tiruvottiyur', label: 'Tiruvottiyur' },
    { value: 'Triplicane', label: 'Triplicane' },
    { value: 'Urapakkam', label: 'Urapakkam' },
    { value: 'Vadapalani', label: 'Vadapalani' },
    { value: 'Valasaravakkam', label: 'Valasaravakkam' },
    { value: 'Vandalur', label: 'Vandalur' },
    { value: 'Vanagaram', label: 'Vanagaram' },
    { value: 'Velachery', label: 'Velachery' },
    { value: 'Villivakkam', label: 'Villivakkam' },
    { value: 'Virugambakkam', label: 'Virugambakkam' },
    { value: 'Vyasarpadi', label: 'Vyasarpadi' },
    { value: 'Washermanpet', label: 'Washermanpet' },
    { value: 'West Mambalam', label: 'West Mambalam' },
    { value: 'Zamin Pallavaram', label: 'Zamin Pallavaram' },
  ];
  